service: analytics-notifications-slack

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  environment:
    ${file(./env.yml)}

custom:
  defaultAccount: dummy
  defaultDigest: dummy
  defaultStage: dev

functions:
  analyticsNotificationsSlack:
    image: ${opt:account, self:custom.defaultAccount}.dkr.ecr.${self:provider.region}.amazonaws.com/analytics_notifications_slack_${self:provider.stage}@${opt:digest, self:custom.defaultDigest}
    events:
      - schedule: cron(0 10 * * ? *) # UTC
