service: analytics-notifications-slack

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  environment:
    ${file(./env.yml)}

custom:
  defaultAccount: dummy
  defaultDigest: dummy
  defaultStage: dev

functions:
  analyticsNotificationsSlack:
    handler: main
    events:
      - schedule: cron(0 10 * * ? *) # UTC
