service: analytics-notifications-slack

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  environment:
    ${file(./env.yml)}

custom:
  defaultStage: dev

functions:
  analyticsNotificationsSlack:
    image: ${opt:account}.dkr.ecr.${self:provider.region}.amazonaws.com/analytics_notifications_slack_${self:provider.stage}@${opt:digest}
    events:
      - schedule: cron(0 10 * * ? *) # UTC
