service: analytics_notifications_slack

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    ${file(./env.yml)}

custom:
  defaultStage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  analytics_notifications_slack:
    handler: bin/handler
    events:
      - schedule: cron(0 10 * * ? *) # UTC
