service: analytics-notifications-slack

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  environment:
    ${file(./env.yml)}

custom:
  defaultStage: dev

package:
  exclude:
    - ./**
  include:
    - ./**

functions:
  analyticsNotificationsSlack:
    handler: bin/handler
    events:
      - schedule: cron(0 10 * * ? *) # UTC
