name: go-sls

on:
  push:
    # FIXME: test on develop branch
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: set up
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: checkout
      uses: actions/checkout@v1

    - name: build
      run: go build -ldflags="-s -w" -o bin/handler handler/main.go

    - name: configure  aws credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: get env
      run: |
        aws s3 cp s3://limit7412-codebuild-envfile/analytics_notifications_slack/dev/env.yml .

    - name: get secret
      run: |
        aws s3 cp s3://limit7412-codebuild-envfile/analytics_notifications_slack/dev/secret.json .

    - name: deploy
      uses: serverless/github-action@master
      with:
        args: deploy --verbose --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
