name: serverless-dev

on: pull_request

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: setup node.js
      uses: actions/setup-node@v1

    - name: install sls
      run: npm i -g serverless

    - name: checkout
      uses: actions/checkout@v1

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: get env
      run: |
        aws s3 cp s3://limit7412-workflow-env/analytics_notifications_slack/dev/env.yml .

    - name: get secret
      run: |
        aws s3 cp s3://limit7412-workflow-env/analytics_notifications_slack/dev/secret.json .

    - name: build
      env:
        REPOSITORY: build-image
      run: |
        docker build -t $REPOSITORY .
        docker run --name $REPOSITORY -d $REPOSITORY /bin/sh
        docker cp $REPOSITORY:/work/main .

    - name: deploy
      run: sls deploy --stage dev