name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: vet
        run: go vet ./...

      - name: test
        run: go test -race ./...
